### ISSUE TITLE
Not so intuitive solution for exercise 25 ?

### ISSUE THREAD

**Issue by rolfschr** [nomeata/haskell-for-readers#14]
In Exercise 25, the reader is expected to implement
``(>=>) :: Monad m => (a -> m b) -> (b -> m c) -> (a -> m c)`` (1)
which the same as the "official" delcaration
``(>=>) :: Monad m => (a -> m b) -> (b -> m c) -> a -> (m c)`` (2).

The presented solution is ``(a >=> b) x = a x >>= b``. I feel like the solution rather "fits" to (2) and ``(>=>) a b = (\x -> a x >>= b)`` (or similar) would be an "appropriate" solution of (1). I understand that this is just a matter of style. I just felt it could be made a bit more intuitive - given the target audience.

**Comment by nomeata** [comment]
Interesting point. I guess at that part of the course, I expect the audience to be somewhat familiar with currying.
