### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by KyleErwin** [nomeata/haskell-for-readers#19]
Hi, this project looks really cool! Would it be possible for you to add a readme with set up instructions and example usage? Thanks.

**Comment by nomeata** [comment]
There is nothing to set up, just go to http://haskell-for-readers.nomeata.de/ and read :-)

**Comment by tejasbubane** [comment]
I just came here from a [reddit comment](https://www.reddit.com/r/haskell/comments/b2fc8e/libraries_to_use_when_writing_a_haskell_book/eishoh0/) and did not know the website exists. It would be useful if you put the website in repo description.

Also it would be great if you can upload the generated PDFs to github releases so users don't have to do all the pandoc installation. I find PDFs useful to refer offline.

**Comment by nomeata** [comment]
The PDFs are liked from http://haskell-for-readers.nomeata.de/. But yeah, I should point people who come here to that webpages.
