### ISSUE TITLE
Dollar can't be defined by anyone

### ISSUE THREAD

**Issue by josephcsible** [nomeata/haskell-for-readers#20]
https://github.com/nomeata/haskell-for-readers/blob/ce06d389c9e648cc5a3e7099ac3aa6362d91cdd7/haskell-for-readers.md#L213

This isn't completely true. In particular, `$` is hardcoded in GHC to support impredicativity in a way that user-defined functions can't. The best-known case of when that matters is when using it with runST. Specifically, this is valid:

```haskell
runST $ do
  return 42
```

But this isn't:
```haskell
runST `myDollar` do
  return 42
```

**Comment by nomeata** [comment]
I know, but that is too much detail at this point of the lecture. And for all purposes of using `($)` in this lecture, it is true that a self-defined `($)` would work.
