### ISSUE TITLE
Spend more time with `data` syntax

### ISSUE THREAD

**Issue by jberryman** [nomeata/haskell-for-readers#3]
I think the syntax for `data` declarations is one of the uglier parts of haskell, and one I see beginners struggle with (and something I remember finding confusing). 

    data Foo a b = Bar Int Char a | Foo 
         \_____/   \_/ \________/   \_/
           Type   Term    Type     Term (n.b. this `Foo` is in a totally 
                                    different namespace from the type `Foo`)

The difficulties are:

- there's a lot of punning going on, with type- and term-level stuff mixed together
- confusing things further, type and data constructors often share the same name (and "constructor" is a kind of unsatisfying overloaded term)
- the `=` is fairly meaningless (note in `type` syntax the `=` actually means `=`, i.e. what we have is a simple type-level function; I think it might make sense to introduce `type` first since the syntax is much more sensible.
- the `|` are unrelated to guards but that might confuse people
- the way the syntax relates to patterns can be confusing, e.g. `Foo a b = ...` looks like a pattern but isn't, likewise `(Bar Int Char)` isn't a valid pattern

I think the most important thing is to make totally clear which parts of the declaration correspond to things that live in _type signatures_ and which things only live _in code_ (maybe by highlighting an example in two different colors). Then you could show a code snippet that uses all the pieces from the declaration with the same highlighting (the type in a type signature, data constructors in both patterns and in RHS).

I don't know how much of the other stuff is necessary to mention/gripe about, but I think it can sometimes be encouraging to learners to hear that something they find confusing or weird is actually confusing/weird/bad.

sorry I don't have a proper edit to suggest right now, but I might be able to open a PR later if you are interested

**Comment by nomeata** [comment]
That’s valuable feedback! Maybe even better without a proper edit, because I am more likely to want to write it in my own words.

If this was a tutorial “how to write Haskell” one could just start with `GADTSyntax` (and explain the other syntax later), but that is not really an option for “how to read Haskell”.
