### ISSUE TITLE
Typos and stuff

### ISSUE THREAD

**Issue by ARPL-c-63h** [nomeata/haskell-for-readers#8]
First time ever I've done anything like this so don't know the protocol. Also non-native English speaker.
- "This document is work in progress" -> **a (?)** work in progress
- "will gain useful insight from tutorial" -> from **this** tutorial
- "The exercises are not sufficient in number and depths" -> **depth**
- "to provide the reader the experience needed" -> **with** the experience
- "are marked with ★" -> with **a (?)** ★
- "Functional program" -> program**ming**
- "Both operator are left-associative" -> operator**s**
- "which is again shorter than" -> **smaller** than
- "no parenthesis or commas needed" -> **parentheses**
- "and less noise code" -> **noisy**
- "If you leave out the parenthesis, you get a horrible error messages" -> If you leave out the parentheses, you can get horrible error messages ... but if you leave out a parenthesis, you can get a horrible error message ... or can get horrible error messages. [So this is about plurals, their spelling and the correct articles associated with them.]
- "the same as parenthesis around the rest of the line" -> **parentheses**
- "because the dollar operator it is not part of the built-in language" -> delete **it**
- "but can be define by anyone" -> define**d**
- "isHalfRound x = x `div` 10 == 0 || x `div` 10 == 5" -> div should be **mod**
   --> Other occurrences: "isEven x = x `div` 10 == 0 || x `div` 10 == 2 || x `div` 10 == 4 || x `div` 10 == 6 || x `div` 10 == 8" "x `div` 10 == y" "hasLastDigit x y = x `div` 10 == y" "x `divides` y = x `div` y == 0"
- Unicode Character 'FULL BLOCK' in "countDigits n = if n < 10 then 1 else █" "countDigits n = if n < 10 then 1 else (n `div` 10)█" "countDigits n = if n < 10 then 1 else countDigits (n `div` 10)█"
- "Use this function and countDigits to write a function isMultipleOf3 so that isMultipleOf3 x is true if repeatedly applying countDigits to x results in 3 or 9."
  "isMultipleOf3 x = fixEq sumDigits x == 3 || fixEq sumDigits x == 6 || fixEq sumDigits x == 9"
  Specification: use countDigits. Implementation uses sumDigits.
- "Instead of defining a countDigits as a function" -> delete first **a**
- "deep and beautiful explanation we write multiple arguments" -> **why (?)** we write
- "composition of a bunch of function" -> function**s**
- "points-free" -> point-free or pointfree?

Section 2 and on later. Unless I'm going about this all wrong ... I'm sure you will let me know in that case.

**Comment by nomeata** [comment]
Thanks! Very helpful. I am surprisingly bad at spotting typos in my own code (because I know what *ought* to be written there) :-)

**Comment by nomeata** [comment]
Fixed. “This is work in progress” is, I believe, an idiom, so I left it. And the █ is intentional, so signify the position of the text cursor as we write the line.

**Comment by ARPL-c-63h** [comment]
You're welcome. So it seems that this way of reporting works; will do the rest in the same way.
I like your take for this tutorial and the build-up you've chosen to present it.
(Issue is closed, but I still reply ... will that work? If not, no harm done.)

**Comment by nomeata** [comment]
It’s actually easier if you simply edit the file: Go to https://github.com/nomeata/haskell-for-readers/blob/master/haskell-for-readers.md and click on the icon with the pen in the top right corner.
